### ISSUE TITLE
suntwins 5000TL

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jcroucher/solarmonj#3]
```
Using solarmonj with a Suntwins 5000TL unit is giving me incorrect readings.

I've captured data to CSV as follows:

1396162955,35.7,18,25.76,384.7,242.2,0.7,4.78,0.8
1396163135,35.6,18,27.12,389.2,283.4,0.7,4.8,0.8
1396163218,35.5,18,26.77,368.5,288.1,0.6,4.81,0.7

According to main.cpp the column order is:

now  << "," <<   data.temperature << "," << data.energyCurrent << "," << 
data.energyToday << "," << data.energyTotal << "," << data.voltageDc << "," <<  
   data.voltageAc << "," << data.frequency << "," << data.current

The 4th column, 'data.energyToday' went backwards on the last reading (from 
27.12 to 26.77). I would expect that counter to always increase. Am I 
mis-reading this?

The other problem is that the values do not match the readout from the unit's 
LCD display. For example, the LCD says 'ETot 301' whereas the corresponding CSV 
values (data.energyTotal) are all higher than this!

Is anyone else using solarmonj with a Suntwins 5000TL?


```

Original issue reported on code.google.com by `porj...@yahoo.com.au` on 30 Mar 2014 at 7:22

**Comment by benleov** [comment]
Hi GoogleCodeExporter, 

Hope you don't mind but I have applied your patch to a [branch](https://github.com/benleov/solarmonj) of this repository.

**Comment by jcroucher** [comment]
Hello all.
Sorry I did not get notified as this was an exported project from Google Code. 
Thanks benleov for fixing the issue. Are there any other issues here or can this be closed now?

**Comment by benleov** [comment]
No worries. I didn't fix the issue, just applied the patch that @GoogleCodeExporter created to my own branch then made a small modification to send the data out a socket which I'm reading into Elasticsearch via Logstash. You guys did all the hard work! As far as I know its working fine.
